version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '3333:3333'
    external_links:
      - mongo
      - postgres
    volumes: ['./:/usr/src/app']
    networks:
      - app-connect

  postgres:
    container_name: postgres
    image: postgres:11
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres-data:/data
    networks:
      - app-connect

  mongo:
    container_name: mongo
    restart: unless-stopped
    image: mongo
    volumes:
      - mongo-data:/data
    ports:
      - '27017:27017'
    networks:
      - app-connect

  redis:
    image: 'redis:alpine'
    hostname: redis
    networks:
      - app-connect
    ports:
      - '6379:6379'

volumes:
  postgres-data:
  mongo-data:

networks:
  app-connect:
    driver: bridge
