version: '3'
services:
  app:
    container_name: backend-pepsico
    restart: always
    build: .
    ports:
      - 3333:3333
      - 9229:9229 #debug port
    external_links:
      - mongo
      - postgres
      - redis
    volumes:
      - ./:/home/node/api
      - ./node_modules:/home/node/api/node_modules
    networks:
      - app-connect

  postgres:
    container_name: postgres-pepsico
    image: postgres:11
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres-data:/data
    networks:
      - app-connect

  mongo:
    container_name: mongo-pepsico
    restart: unless-stopped
    image: mongo
    volumes:
      - mongo-data:/data
    ports:
      - '27017:27017'
    networks:
      - app-connect

  redis:
    container_name: redis-pepsico
    image: 'redis:alpine'
    hostname: redis
    networks:
      - app-connect
    ports:
      - '6379:6379'

volumes:
  postgres-data:
  mongo-data:

networks:
  app-connect:
    driver: bridge
